### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by liminaire-x** [hj613/Book-recommender#1]
## 재현 단계 🚶‍♂️

1. 
2.
3.

## 환경 🖥️
- OS 버전:
- 브라우저 버전:
- 기타:

**Comment by hj613** [comment]
좋습니다 추후 구현 시 이슈 양식 유용하게 사용할 수 있을 것 같습니다~

**Comment by liminaire-x** [comment]
확인했습니다. 이제 이 이슈는 닫겠습니다
