### ISSUE TITLE
[Template] 수정 사항 여부

### ISSUE THREAD

**Issue by liminaire-x** [hj613/Book-recommender#5]
## 설명 📝
템플릿을 작성했는데, 어떤지 궁금합니다 [f98bc74] [b52bf8e]을 보면 됩니다.

## 예상 동작 🤔
-
## 실제 동작 ❌
-

## 재현 단계 🚶‍♂️
-

## 환경 🖥️
- OS 버전: 윈도우
- 브라우저 버전: x
- 기타:x

## 스크린샷 📷
-

**Comment by hj613** [comment]
템플릿 완전 깔끔하고 좋습니다!

**Comment by hj613** [comment]
file Template 현재 main.py랑 연계해서 어떻게 사용할지 보고 있습니다

**Comment by hj613** [comment]
close #63f90a7
파일 내용 수정 완료
